package org.jarbframework.constraint.violation.resolver;

import static org.jarbframework.constraint.violation.DatabaseConstraintType.INVALID_TYPE;
import static org.jarbframework.constraint.violation.DatabaseConstraintType.LENGTH_EXCEEDED;
import static org.jarbframework.constraint.violation.DatabaseConstraintType.NOT_NULL;
import static org.jarbframework.constraint.violation.DatabaseConstraintType.UNIQUE_KEY;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.sql.DataSource;

import org.jarbframework.constraint.violation.DatabaseConstraintViolation;
import org.jarbframework.constraint.violation.domain.User;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

/**
 * Check that a "default" constraint violation resolver works on errors generated by our HSQL driver.
 * For the resolver to work, it has to correctly recognize our database as HSQL and interpret the
 * provided exception messages as constraint violation information.
 * 
 * @author Jeroen van Schagen
 * @since 16-05-2011
 */
@Transactional
@RunWith(SpringJUnit4ClassRunner.class)
@ActiveProfiles("hsqldb")
@ContextConfiguration(locations = { "classpath:application-context.xml" })
public class DatabaseConstraintViolationResolverFactoryTest {
    
    private DatabaseConstraintViolationResolver violationResolver;

    @Autowired
    private DataSource dataSource;

    @PersistenceContext
    private EntityManager entityManager;

    @Before
    public void setUpResolver() {
        violationResolver = new DatabaseConstraintViolationResolverFactory().build(dataSource);
    }

    /**
     * Column "name" cannot be null.
     */
    @Test
    public void testNotNull() {
        User user = new User(null);
        try {
            entityManager.persist(user);
            fail("Expected a runtime exception");
        } catch (RuntimeException e) {
            DatabaseConstraintViolation violation = violationResolver.resolve(e);
            assertEquals(NOT_NULL, violation.getConstraintType());
            assertTrue(violation.getConstraintName().startsWith("sys_ct_"));
            assertEquals("users", violation.getTableName());
            assertEquals("name", violation.getColumnName());
        }
    }

    /**
     * Column "name" is expected to be unique.
     */
    @Test
    public void testUniqueKey() {
        entityManager.persist(new User("admin"));
        try {
            entityManager.persist(new User("admin"));
            fail("Expected a runtime exception");
        } catch (RuntimeException e) {
            DatabaseConstraintViolation violation = violationResolver.resolve(e);
            assertEquals(UNIQUE_KEY, violation.getConstraintType());
            assertEquals("uk_users_name", violation.getConstraintName());
            assertEquals("users", violation.getTableName());
        }
    }

    /**
     * Column "name" has a maximum length of '10'.
     */
    @Test
    public void testLengthExceeded() {
        try {
            entityManager.persist(new User("superlongusername"));
            fail("Expected a runtime exception");
        } catch (RuntimeException e) {
            DatabaseConstraintViolation violation = violationResolver.resolve(e);
            assertEquals(LENGTH_EXCEEDED, violation.getConstraintType());
        }
    }

    /**
     * Column "active" is a boolean in the database, not a string.
     */
    @Test
    public void testInvalidType() {
        User jeroen = new User("Jeroen");
        jeroen.setActive("not a boolean");
        try {
            entityManager.persist(jeroen);
            fail("Expected a runtime exception");
        } catch (RuntimeException e) {
            DatabaseConstraintViolation violation = violationResolver.resolve(e);
            assertEquals(INVALID_TYPE, violation.getConstraintType());
        }
    }

}
